name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: NicolasBradley
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push generated snake files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake animation"
          add: "dist/*.svg dist/*.gif"
