name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:      # manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: NicolasBradley
          outputs: |
            ./assets/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
